# nixpacks.toml
[variables]
PHP_VERSION = "8.1"

[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'composer dump-autoload --optimize'
]

[phases.build]
cmds = ['echo "PHP application ready"']

[start]
cmd = 'php -S 0.0.0.0:$PORT'